### ISSUE TITLE
Implement UI Redesign

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/SpeedRunEthereum#175]
**Subtasks**

- [x] Homepage Header (@carletex on https://github.com/BuidlGuidl/SpeedRunEthereum/pull/176)
![image](https://user-images.githubusercontent.com/2486142/202491526-3c124982-d8e3-4f31-a393-9d2575c02329.png)

- [x] Challenge teaser (ChallengeExpandedCard.jsx) (@technophile-04).
![image](https://user-images.githubusercontent.com/2486142/202491660-1ce11a2c-c570-43ee-9849-adf498d783c2.png)

- [x] Join the BG. It has a different styling
![image](https://user-images.githubusercontent.com/2486142/202492999-737a1282-6a49-4759-bfce-fa0366a3ebb7.png)

- [x] Challenge detail page (still not designed)
- [x] Builder Portfolio (still not designed)

**Approach**
- We'd be using ChakraUI props to implement the design (no need to write CSS / inline styles)
- Global variables (colors, etc.) will be set using global Chakra config (no inline hard-coding)
- Keep in mind the dark mode (check Figma)

**Figma**
https://www.figma.com/file/LXP80HTaLU57McsiC6aVll/Speedrun-Ethereum?t=sOI3MV9wXHqHM7Ne-0

**Staging site**
https://staging.speedrunethereum.com/

The `staging` branch is automatically deployed here. We'll be merging everything there (so anyone can test & see progress.)

Once ready we'll merge staging into master

![photo1667488790](https://user-images.githubusercontent.com/2486142/202490373-89ec0bfe-0e50-4d50-b1e8-00ea27ec6902.jpeg)
![photo1667488790 (1)](https://user-images.githubusercontent.com/2486142/202490367-3efbfdd1-5521-4e28-ae95-f6bbd4344a1d.jpeg)

**Comment by carletex** [comment]
Fixed on #182
